In [ ]:
# Segmentation is where we take photos and we colour in every pixel according to what it is.

In [ ]:
# In fastai, SegmentationDataLoaders is a high-level factory class designed to quickly load image segmentation datasets (where pixel-level masks correspond to input images). Y

In [ ]:
path = untar_date(URLs.CAMVID_TINY)

In [ ]:
# The untar_data function in the fastai library safely downloads a compressed dataset URL, extracts it into your ~/.fastai/data/ directory, and returns a pathlib Path object pointing to the extracted files. It prevents re-downloading if the files already exist

In [ ]:
# In course_nb.ipynb we used data blocks which are a kind of intermediate level, very flexible
# approach that can be taken to handle amost any kind of data. But for the kinds of data that occur
# a lot, we can use special data loaders claseses which kind of let us use even less code.

In [1]:
# label_func gets the paths 
# codes gets the labels for further segmentation - what does each code mean?

dls = SegmentationDataLoaders.from_label_func(
    path, bs=8, fnames=get_image_file(path."images"),
    label_func=lambda o: path/'labels'/f'{o.stem}_P{o.suffix}',
    codes=np.loadtxt(path/'codes.txt', dtypes=str)

_IncompleteInputError: incomplete input (1385556844.py, line 1)

In [ ]:
learn = unet_learner(dls, resnet34)
learn.fine_tune(8)

In [ ]:
# Tabular analysis is the most widely used alongside data like that from spreadsheets

In [4]:
from fastai.tabular.all import *

In [5]:
# untar_data downloads some data and decompresses it
# There are a lot of URLs provided by fastai for all kinds of common data sets that can be used

path = untar_data(URLs.ADULT_SAMPLE)

```html
<div>
<progress max="968212" value="974848"></progress> 100.69% [974848/968212 00:03&lt;00:00]</div>

```

In [6]:
# We need to tell TabularDataLoaders which of the columns are categorical (cat_names), and 
# which ones are continuos (cont_names)(can take any real number)

dls = TabularDataLoaders.from_csv(path/'adult.csv', path=path, y_names="salary",
                                  cat_names = ['workclass','education','marital-status','occupation','relationship'],
                                  cont_names = ['age', 'fnlwgt', 'education-num'],
                                  procs = [Categorify, FillMissing, Normalize])

dls.show_batch()

/home/vaishnavi-asawale/.local/lib/python3.14/site-packages/fastai/torch_core.py:155: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /__w/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  else as_tensor(x.values, **kwargs) if isinstance(x, (pd.Series, pd.DataFrame))

In [7]:
# Fastai has something called "type dispatch" which is a system that's particularly popluar in a
# language called Julia to basically automatically, do the right thing for your data regardless of what
# kind of data it is. So if you call show_batch(), we should get batch something "useful"

In [8]:
learn = tabular_learner(dls, metrics=accuracy)
learn.fit_one_cycle(2)
# We don't call fine_tune, we use fit
# That's because for tabular data there won't be any pre-trained model for that sort of data
# Because every table of data is very different, whereas pictures have the same sort of "idea"

<div><table class="fastprogress"><thead><tr><th>epoch</th><th>train_loss</th><th>valid_loss</th><th>accuracy</th><th>time</th></tr></thead><tbody><tr><td>0</td><td>0.366049</td><td>0.362535</td><td>0.830160</td><td>00:04</td></tr><tr><td>1</td><td>0.354472</td><td>0.351474</td><td>0.833692</td><td>00:04</td></tr></tbody></table></div>

In [ ]:
# Collaborative filtering - the foundation of recommendation systems
# It's a system where we basically take a data set that says which users liked/ used which 
# products, and then we use that to guess what other producs those users might like based on finding 
# similar users, and what those similar users like

In [10]:
from fastai.collab import *

path = untar_data(URLs.ML_SAMPLE)
dls = CollabDataLoaders.from_csv(path/'ratings.csv')

```html
<div>
<progress max="51790" value="57344"></progress> 110.72% [57344/51790 00:00&lt;00:00]</div>

```

In [11]:
dls.show_batch()

In [13]:
# Collaborative data has some kind of user_id, some product_id (movie), and a rating

# Since this is not predicting a cateogry but a real number, we tell it the possible range (y_range)
# The actual range is 1-5, but it is a good idea to add some padding (0.5 - 5.5)
learn = collab_learner(dls, y_range=(0.5, 5.5))
learn.fine_tune(10) # fit can also be used

<div><table class="fastprogress"><thead><tr><th>epoch</th><th>train_loss</th><th>valid_loss</th><th>time</th></tr></thead><tbody><tr><td>0</td><td>1.496672</td><td>1.369415</td><td>00:00</td></tr></tbody></table></div>

<div><table class="fastprogress"><thead><tr><th>epoch</th><th>train_loss</th><th>valid_loss</th><th>time</th></tr></thead><tbody><tr><td>0</td><td>1.397873</td><td>1.317113</td><td>00:00</td></tr><tr><td>1</td><td>1.285793</td><td>1.165504</td><td>00:01</td></tr><tr><td>2</td><td>1.058627</td><td>0.879739</td><td>00:01</td></tr><tr><td>3</td><td>0.822068</td><td>0.714031</td><td>00:01</td></tr><tr><td>4</td><td>0.703935</td><td>0.675692</td><td>00:00</td></tr><tr><td>5</td><td>0.659686</td><td>0.666682</td><td>00:00</td></tr><tr><td>6</td><td>0.630955</td><td>0.659062</td><td>00:00</td></tr><tr><td>7</td><td>0.624529</td><td>0.655287</td><td>00:01</td></tr><tr><td>8</td><td>0.597424</td><td>0.654959</td><td>00:01</td></tr><tr><td>9</td><td>0.614137</td><td>0.654828</td><td>00:00</td></tr></tbody></table></div>

In [14]:
# Valid loss is the mean squared error, and it goes down each epoch

learn.show_results()